Add check for /etc/fstab
hashicorp/vagrant pull request #11897
Opened 2020-09-10 14:58 UTC by soapy1

fixes https://github.com/hashicorp/vagrant/issues/11894

2020-09-10 16:34 UTC, dcermak approved these changes
I have tested this locally with a box that lacked a /etc/fstab and the issue is resolved by that.

2020-09-10 22:46 UTC, chrisroberts requested changes

2020-09-10 22:46 UTC, chrisroberts commented on plugins/guests/linux/cap/persist_mount_shared_folder.rb
> +          machine.communicate.test("stat /etc/fstab")
Can we simplify this down to just `test -f /etc/fstab` ?

2020-09-10 22:46 UTC, chrisroberts commented on plugins/guests/linux/cap/persist_mount_shared_folder.rb
> +          unless fstab_exists?(machine)
Update the `unless` to an `if !fstab_exists?` simply due to the overall preference for `if` based conditionals

2020-09-14 23:18 UTC, chrisroberts approved these changes

2020-09-15 14:57 UTC, merged

2020-09-15 15:26 UTC, marga-kinvolk commented
Thanks for working on this fix!

I do find the logic of this change a bit strange. If `/etc/fstab` doesn't exist, it bails out of doing the additions that it was planning to do. It would be fine to create an `/etc/fstab` that doesn't exist. At least in Flatcar it doesn't exist because all the OS mounts are managed by systemd, not because creating it doesn't work.

In other words, I think the check should be inside `remove_vagrant_managed_fstab` rather than on the whole function.

Thanks again.

2020-09-15 20:18 UTC, soapy1 commented
@marga-kinvolk thanks for following up about this!
It seems I have misunderstood the interactions between `/etc/fstab` and systemd. It seems desirable to allow Vagrant to modify fstab regardless of if systemd is being used to manage mounts. Going to push up a change in a little bit 🚀 

ref: https://docs.flatcar-linux.org/os/kernel-modules/#create-a-writable-overlay