Add contributing style guide
hashicorp/vagrant pull request #11914
Opened 2020-09-17 22:06 UTC by soapy1

2020-09-18 20:03 UTC, briancain requested changes

2020-09-22 17:07 UTC, chrisroberts requested changes
This looks great!

2020-09-22 17:07 UTC, chrisroberts commented on .github/CONTRIBUTING.md
> +Next, cd into that path. All commands will be run from this path:
Next, move into the newly created `./vagrant directory:

```
$ cd ./vagrant
```

All commands will be run from this path. Now, run the `bundle` command to install the Ruby dependencies:

```
$ bundle install
```

2020-09-22 17:07 UTC, chrisroberts commented on .github/CONTRIBUTING.md
>  * If possible, submit tests along with your topic branch. It will help a lot to get your your patch / new feature accepted, and should prevent unwanted breaking changes to silently happen in future d
We should update the wording here as tests being _required_ unless they are not applicable for some reason (like docs changes, dependency constraint updates, etc).

2020-09-22 17:07 UTC, chrisroberts commented on .github/CONTRIBUTING.md
> +If you are developing Vagrant on a machine that already has a Vagrant package installation present, both will attempt to use the same folder for their configuration (location of this folder depends o
> before running any commands, to be some new

That comma can be removed.

2020-09-24 21:36 UTC, chrisroberts submitted a review, later dismissed
Two small quick changes but feel free to merge after.

2020-09-24 21:36 UTC, chrisroberts commented on .github/CONTRIBUTING.md
> +Next, move into the newly create `./vagrant` directory. All commands will be run from this path:
~All commands will be run from this path:~

`create` -> `created`

2020-09-30 14:33 UTC, merged