Always use upstream Salt bootstrap script on Windows
hashicorp/vagrant pull request #12127
Opened 2021-01-04 03:36 UTC by max-arnold

Get rid of outdated `bootstrap-salt.ps1` script and instead always use the upstream one. Fixes https://github.com/hashicorp/vagrant/issues/11394

The upstream script is available at https://github.com/saltstack/salt-bootstrap/blob/stable/bootstrap-salt.ps1 and https://winbootstrap.saltstack.com

2021-01-04 03:36 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/vagrant?pullRequest=12127)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/vagrant?pullRequest=12127)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/vagrant?pullRequest=12127).</sub>

2021-01-04 18:10 UTC, dafyddj commented
Can I suggest downloading `upstream_bootstrap.ps1` to a temporary directory?
Otherwise it downloads and runs from `C:\Users\<user>\Documents`.

2021-01-04 18:50 UTC, max-arnold commented
My goal was to download it to the same directory where Vagrant uploads its embedded bootstrap script (for easier debugging). Tomorrow I'll double check that.

2021-01-05 22:04 UTC, UtahDave submitted a review, later dismissed
Looks great to me. This will ensure the latest Salt version is always installed.

2021-01-06 09:05 UTC, max-arnold commented
@dafyddj I can confirm that right now the upstream script is downloaded to Documents. I'm going to update the PR so the download folder will be `C:\tmp` (the same where other Vagrant files are uploaded). Thanks for noticing this!

2021-01-06 15:04 UTC, max-arnold commented
I updated the built-in bootstrap script so it downloads the upstream one into the same directory (`C:\tmp`) without polluting the `Documents` folder.

A couple of things for reviewers to double-check:

1. Is `Tls12,Tls13` line really necessary and will it work on all PowerShell versions?
2. Is it worth replacing custom `$ScriptRoot` variable with the built-in `$PSScriptRoot` that is only available on PowerShell 3.0+?  In other words, can we assume that any Windows version supported by Salt ships with PowerShell 3.0 or greater?

2021-01-06 16:16 UTC, UtahDave commented
> 2. Is it worth replacing custom `$ScriptRoot` variable with the built-in `$PSScriptRoot` that is only available on PowerShell 3.0+?  In other words, can we assume that any Windows version supported by Salt ships with PowerShell 3.0 or greater?

Supported Operating Systems:
https://get.saltstack.com/rs/304-PHQ-615/images/SaltStack-Supported-Operating-Systems.pdf

According to this wikipedia article, Powershell 3 comes with Windows 8 and Windows Server 2012 by default:
https://en.wikipedia.org/wiki/PowerShell#Windows_PowerShell_3.0

So it looks like it might be possible that Windows Server 2008 might not have Powershell 3.0 unless the user installs it first. I haven't tested this theory, though.

2021-01-06 18:04 UTC, twangboy requested changes

2021-01-06 18:04 UTC, twangboy commented on plugins/provisioners/salt/bootstrap-salt.ps1
> +(New-Object System.Net.WebClient).DownloadFile('https://winbootstrap.saltstack.com', "${ScriptRoot}\bootstrap_salt_upstream.ps1")
Please use `winbootstrap.saltproject.io`

2021-01-09 00:36 UTC, twangboy approved these changes

2021-02-04 22:31 UTC, soapy1 commented
> Is it worth replacing custom $ScriptRoot variable with the built-in $PSScriptRoot that is only available on PowerShell 3.0+? In other words, can we assume that any Windows version supported by Salt ships with PowerShell 3.0 or greater?

Vagrant's minimum powershell version is 3. So, yep this is a safe assumption

2021-05-23 12:51 UTC, max-arnold commented
@soapy1 It's been a while since I submitted this PR. Is there anything I can do to get it merged?

2021-05-24 21:49 UTC, soapy1 approved these changes

2021-05-24 21:49 UTC, soapy1 commented
Looks good, thanks for the gentle nudge!

2021-05-24 21:49 UTC, merged

2021-06-03 18:03 UTC, leon-kleyn commented
@max-arnold I am not sure if this is the right place to ask, but how can I go about implementing this? Currently using latest version of Vagrant and Vagrantfile to provision salt on a Windows box. It keeps pulling C:\tmp/bootstrap_salt.ps1 and Salt-Minion-2018.3.3-Py2-AMD64-Setup.exe, which then promptly fails.

2021-06-03 18:24 UTC, max-arnold commented
@leon-kleyn You still see the problem because this fix is not yet released. It will be available in Vagrant 2.2.17.

If you can't wait, grab the [fixed script](https://github.com/hashicorp/vagrant/blob/main/plugins/provisioners/salt/bootstrap-salt.ps1), place it alongside your Vagrantfile, and then use like this:

```ruby
  config.vm.define "minion" do |minion|
    minion.vm.provision :salt do |salt|
      salt.minion_config = "salt/etc/minion"
      salt.bootstrap_script = "./bootstrap-salt.ps1"
      salt.verbose = true
      salt.colorize = true
      salt.version = "3003"
      salt.python_version = "3"
    end
  end
```

2021-06-03 18:29 UTC, leon-kleyn commented
@max-arnold thank you, will give that a shot! On https://www.vagrantup.com/docs/provisioning/salt, it states bootstrap_script is not supported on Windows, I assume these docs are out of date?

2021-06-03 18:35 UTC, max-arnold commented
It is (and was) supported. I fixed the docs as part of this PR as well.

2021-06-04 19:36 UTC, leon-kleyn commented
@max-arnold all that worked for me, thanks again. I do get an error in the middle of bootstrapping Salt on Windows box using this script locally:

`Bootstrapping Salt... (this may take a while)
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

powershell.exe -NonInteractive -NoProfile -executionpolicy bypass -file C:\tmp/bootstrap_salt.ps1  -version 3003 -pythonVersion 3

Stdout from the command:

Downloading Salt minion installer Salt-Minion-3003-Py3-AMD64-Setup.exe
Installing Salt minion
Starting the Salt minion service
Salt minion successfully installed


Stderr from the command:

powershell.exe : Cannot convert value "Tls12,Tls13" to type "System.Net.SecurityProtocolType". Error: "Unable to
    + CategoryInfo          : NotSpecified: (Cannot convert ...or: "Unable to :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
match the identifier name Tls12,Tls13 to a valid enumerator name. Specify one of the following
enumerator names and try again:
SystemDefault, Ssl3, Tls, Tls11, Tls12"
At C:\tmp\bootstrap_salt.ps1:2 char:1
+ [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.Secu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : SubstringDisambiguationEnumParseThrewAnException`
    
Vagrant and Salt appear to be functioning properly despite this error. The only thing this affects is if I am trying to 'vagrant up' multiple minions, the process stops after this error and does not move on to the next minion. I am using latest Vagrant and latest Virtualbox, using a Windows-2019 box.

2021-06-05 07:26 UTC, max-arnold commented
I only tested this line on Windows 10:

```
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]'Tls12,Tls13'
```

Apparently, `Tls13` enum is not available in your Windows-2019 box. This constant was added in .NET Framework 4.8. If you (or other folks who are reading this) have some time, could you please try running the following command in PowerShell (as administrator) on different Windows and .NET Framework versions:

```
(New-Object System.Net.WebClient).DownloadFile('https://winbootstrap.saltstack.com', "C:\bootstrap_salt_upstream.ps1")
```

It works for me on Windows 10 just fine without the problematic `Tls12,Tls13` line. If you can confirm that `DownloadFile` works on reasonably wide range of supported WIndows versions, we can just drop this line.

https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.securityprotocol?view=net-5.0
https://docs.microsoft.com/en-us/dotnet/api/system.net.securityprotocoltype?view=net-5.0#System_Net_SecurityProtocolType_SystemDefault
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

2021-06-08 15:44 UTC, dafyddj commented
@max-arnold the line `(New-Object System.Net.WebClient).DownloadFile('https://winbootstrap.saltstack.com', "C:\bootstrap_salt_upstream.ps1)` fails on Windows 8.1, which is still supported until Jan 2023.

In addition, the enumerations are limited to `Tls12` at a maximum. (With the out of the box .Net 4.5.1)
```
PS C:\Users\vagrant> [System.Net.ServicePointManager]::SecurityProtocol = 15360
Exception setting "SecurityProtocol": "Cannot convert value "15360" to type "System.Net.SecurityProtocolType" due to
enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible
enumeration values are "Ssl3, Tls, Tls11, Tls12"."
```

2021-06-08 16:29 UTC, max-arnold commented
@dafyddj Thanks for testing this!

I'm going to submit another PR that will only use Tls12 enum