openbsd: rsync switch to nluug.nl
hashicorp/vagrant pull request #12656
Opened 2022-01-18 22:08 UTC by zhanhb

to support more versions

2022-01-18 22:08 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/vagrant?pullRequest=12656)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/vagrant?pullRequest=12656)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/vagrant?pullRequest=12656).</sub>

2022-07-27 20:38 UTC, chrisroberts requested changes
I don't think that changing from the openbsd site for this download is the best here. I think a better solution would be to surface source as a configurable value which defaults to the current openbsd site.

2022-07-27 23:41 UTC, chrisroberts commented
Related: #12510

2022-11-18 19:43 UTC, phinze commented
Going to close this PR, but a different one that made this value configurable would still be welcome.

2022-11-18 19:43 UTC, closed without merging