Docs Updates to Follow Style Guides.
hashicorp/vagrant pull request #12924
Opened 2022-09-28 17:56 UTC by kaitlincart

2022-09-30 14:28 UTC, tunzor requested changes
Just a few language changes but otherwise LGTM 👍

2022-09-30 14:28 UTC, tunzor commented on website/content/docs/installation/index.mdx
> +To get started with Vagrant, you will need to download the appropriate installer or
```suggestion
To get started with Vagrant, download the appropriate installer or
```

2022-09-30 14:28 UTC, tunzor commented on website/content/docs/installation/index.mdx
> +The installer should automatically add `vagrant` to your system path
```suggestion
The installer automatically adds `vagrant` to your system path
```

2022-09-30 14:28 UTC, tunzor commented on website/content/docs/installation/index.mdx
> +If you have more than one hypervisor is in use, hypervisors often do not allow you to bring up virtual machines.
```suggestion
Hypervisors often do not allow you to bring up virtual machines if you have more than one hypervisor in use.
```

2022-09-30 14:28 UTC, tunzor commented on website/content/docs/installation/index.mdx
> +You must denylist the additional hypervisors in order for VirtualBox to run correctly.
```suggestion
You must add the additional hypervisors to the deny list in order for VirtualBox to run correctly.
```
`Denylist` as a verb sounds odd to me but feel free to keep it as I learned today that it is, in fact, a verb 😅

2022-09-30 14:28 UTC, tunzor commented on website/content/docs/installation/index.mdx
> +Use the `blacklist` command to add the hypervisor to you denylist.
```suggestion
Use the `blacklist` command to add the hypervisor to your denylist.
```

2022-09-30 14:28 UTC, tunzor commented on website/content/docs/installation/upgrading.mdx
> +If you encounter any problems at upgrade time, [report them issue in Github](https://github.com/hashicorp/vagrant/issues). Upgrades are meant to be a smooth process and we consider it a bug if it was
```suggestion
If you encounter any problems at upgrade time, [report them as an issue in Github](https://github.com/hashicorp/vagrant/issues). Upgrades are meant to be a smooth process and we consider it a bug if it was not.
```

2022-09-30 16:09 UTC, tunzor approved these changes
👍

2022-10-03 15:40 UTC, soapy1 approved these changes

2022-10-04 16:24 UTC, merged