Update provider/virtualbox to allow paused state when booting vm
hashicorp/vagrant pull request #13496
Opened 2024-08-29 21:13 UTC by allisonlarson

When a virtualbox vm is booting initially, allow it to enter the `:paused` state and wait until a new state is entered or the boot_timeout is reached. This allows the GUI menu to be accessed and state selected before it errors, but to still error as expected if the outcome of the selection moves the vm to an invalid state. This matches how previous versions of virtualbox behaved, before the `:paused` state was introduced.

fixes #13410

2024-09-10 16:54 UTC, chrisroberts requested changes
This change looks great. Just one style nit in the tests, and I'll approve after since they get auto-dismissed on push.

2024-09-10 16:54 UTC, chrisroberts commented on test/unit/vagrant/action/builtin/wait_for_communicator_test.rb
> +    to_not raise_error()
Just a small style nit, would you remove the parens on the `raise_error` here since there are no parameters being passed.

2024-09-11 17:39 UTC, chrisroberts approved these changes
Thanks!

2024-09-23 19:04 UTC, merged

2024-10-18 09:48 UTC, nurrony commented
https://github.com/hashicorp/vagrant/pull/13496